### ISSUE TITLE
Create pl-heudiconv repo in the rh-impact organization repos

### ISSUE THREAD

**Issue by rudolphpienaar** [rh-impact/pnt-hackathon-2022#75]

**Comment by grdryn** [comment]
@rudolphpienaar I've assigned this task to myself since the corresponding "containerize and deploy" and "document" tasks don't seem to be here for it. Shall I create them? Thanks! 🙏

**Comment by rudolphpienaar** [comment]
Oh! Yes, please. It was on my todo-list but I forgot. I'm happy to also chat a tad about this task. The BIDS data structure/format is used by lots of neuroscience(y) apps and have a plugin that can pack data into BIDS would be rather useful.

**Comment by grdryn** [comment]
@rudolphpienaar thanks a lot for your response! I've created those now (#76 and #77).

> I'm happy to also chat a tad about this task. The BIDS data structure/format is used by lots of neuroscience(y) apps and have a plugin that can pack data into BIDS would be rather useful.

From a couple of minutes reading up on heudiconv, it seems like there are a few things that it can do. When you say that it would be useful to have a plugin that can pack data into BIDS, is that what you would expect as the primary function of this plugin (rather than DICOM -> NIfTI conversion (these formats/specs are not familiar to me yet, so please excuse me if what I'm asking doesn't make much sense yet 🙂)), or are you suggesting a different generic BIDS plugin would also be useful?

I've also joined the `#chris-redhatimpact:fedora.im` room in Matrix, so feel free to contact me there if that's a preferable place to discuss (note that I'm in Ireland though, so I may not be very responsive for the next few hours).

**Comment by adithyaakrishna** [comment]
Created a new one at, https://github.com/rh-impact/pl-heudiconv

**Comment by grdryn** [comment]
Thanks a lot @adithyaakrishna! 😃

**Comment by adithyaakrishna** [comment]
Closing this as the Repo is created :)
